(
  SELECT CITY, LENGTH(CITY) AS name_length
  FROM STATION
  ORDER BY LENGTH(CITY), CITY
  LIMIT 1
)
UNION
(
  SELECT CITY, LENGTH(CITY) AS name_length
  FROM STATION
  ORDER BY LENGTH(CITY) DESC, CITY
  LIMIT 1
);
